trigger:
  branches:
    include:
      - master
      - beta
      - release/beta/*
      - stable
      - release/stable/*

pr:
  branches:
    include:
      - master
      - beta
      - release/beta/*
      - stable
      - release/stable/*

resources:
  containers:
  - container: nv-bionic-wasm
    image: unoplatform/wasm-build:3.0

jobs:

- job: iOS_Tests
  variables:
    CI_Build: true
    SourceLinkEnabled: false
    XCODE_ROOT: /Applications/Xcode_14.2.app

  pool:
    vmImage: 'macOS-12'

  steps:
  - checkout: self
    clean: true

  - bash: /bin/bash -c "sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_12_18"
    displayName: Select Xamarin Version

  - bash: /bin/bash -c "echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'${XCODE_ROOT};sudo xcode-select --switch ${XCODE_ROOT}/Contents/Developer"
    displayName: Select Xcode

  - bash: |
      chmod +x $(build.sourcesdirectory)/build/ios-uitest-run.sh
      $(build.sourcesdirectory)/build/ios-uitest-run.sh

    displayName: Build and Run iOS Test

    env:
      BUILD_SOURCESDIRECTORY: "$(build.sourcesdirectory)"
      BUILD_ARTIFACTSTAGINGDIRECTORY: "$(build.artifactstagingdirectory)"

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testRunTitle: 'iOS Test Run'
      testResultsFormat: 'NUnit'
      testResultsFiles: '$(build.sourcesdirectory)/build/TestResult.xml'

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: uno-uitest-tests
      ArtifactType: Container
